# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66ecd7e1fa2f3d8c91ec7cec945c067f685116cce9999ca096a9acf3fdfdb40c6c6fbcb096343d0272af1836fd0ce2099154aa809c8fc7fca2d00687ce9392c5

test:
  secret_key_base: 563c9c4842d622edb7833a195707498df8e6011d382899cde1a4d69850081fc86eb187c6121d1dcc189f05a9ddad664c8a369a9e2aae10a022cf4a8caf17cadb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
